version: '3.4'

services:
  frontend:
    build:
      context: ./docker/local
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - residential-meeting-admin

networks:
  residential-meeting-admin:
    name: residential-meeting-admin_default
    external: true
